In [1]:
import pandas as pd

packed = pd.DataFrame([['banana', 'long|yellow'], 
                       ['kiwi', 'brown|oval']], 
                      columns=['FRUIT', 'ATTRIBUTES'])

pack_delim = '|'

per_fruit_frames = []

In [2]:
packed

    FRUIT   ATTRIBUTES
0  banana  long|yellow
1    kiwi   brown|oval

In [3]:
# for row in packed.itertuples(index=True, name='Pandas'):
#     row_attribs = row.ATTRIBUTES
#     row_attribs_split = row_attribs.split(pack_delim)
#     row_attribs_series = pd.Series(row_attribs_split)
#     ras_len = len(row_attribs_split)
#     fruit_rep = [row[1]] * ras_len
#     frs = pd.Series(fruit_rep)
#     temp = pd.concat([frs, row_attribs_series], axis=1)
#     per_fruit_frames.append(temp)
    
# unpacked = pd.concat(per_fruit_frames)

# unpacked.columns = packed.columns

In [4]:
unpacked = packed.copy()

unpacked['ATTRIBUTES']=unpacked['ATTRIBUTES'].str.split('|')
unpacked=unpacked.explode('ATTRIBUTES',ignore_index=True)

In [5]:
unpacked

    FRUIT ATTRIBUTES
0  banana       long
1  banana     yellow
2    kiwi      brown
3    kiwi       oval

In [6]:
repacked = unpacked.groupby(['FRUIT']).agg({'ATTRIBUTES': '|'.join}).reset_index()

In [7]:
repacked

    FRUIT   ATTRIBUTES
0  banana  long|yellow
1    kiwi   brown|oval